export const PATH_HOME_PAGE              = '/'
export const PATH_AUTH_PAGE              = '/auth'
export const PATH_ACCOUNT_PAGE           = '/account'
export const PATH_CART_PAGE              = '/cart'
export const PATH_CATALOG_PAGE           = '/catalog'
export const PATH_CHECKOUT_PAGE          = '/checkout'